name: Daily kata

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 14 * * *" 

permissions:
  contents: write

jobs:
  commit-kata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Configure git author (your verified info)
        run: |
          git config user.name "Don Doricent"
          git config user.email "ddoricent97@gmail.com"

      # TODO: add your step(s) that create/update your Codewars files here

      - name: Commit and push if changed (UTC timestamp)
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Daily kata $(date -u +'%Y-%m-%d')"
            git push origin HEAD:main
          fi
